name: Docker Build and Push

on:
  push:
    branches:
      - main

# env:
# #   IMAGE_NAME: gocodify/internal/node
#   REGISTRY: docker.io/gocodify/external

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login $REGISTRY -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and tag Docker image
        run: docker build -t gocodify/external:node .
#         run: docker build -t $REGISTRY/$IMAGE_NAME:${{ github.sha }} .

      - name: Push Docker image
        run: docker push gocodify/external:node
#         run: docker push $REGISTRY/$IMAGE_NAME:${{ github.sha }}
